#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFF584E5967A1DA7B (djmaecki@ull.at)
#
Name     : wol
Version  : 0.7.1
Release  : 1
URL      : https://downloads.sourceforge.net/project/wake-on-lan/wol/0.7.1/wol-0.7.1.tar.gz
Source0  : https://downloads.sourceforge.net/project/wake-on-lan/wol/0.7.1/wol-0.7.1.tar.gz
Source99 : https://downloads.sourceforge.net/project/wake-on-lan/wol/0.7.1/wol-0.7.1.tar.gz.asc
Summary  : The Wake On Lan client.
Group    : Development/Tools
License  : GPL-2.0
Requires: wol-bin
Requires: wol-doc
Requires: wol-locales
BuildRequires : bison

%description
This is wol, the Wake On Lan client. It wakes up magic packet compliant
machines such as boxes with wake-on-lan ethernet-cards. Some workstations
provides SecureON which extends wake-on-lan with a password. This feature
is also provided by wol.

%package bin
Summary: bin components for the wol package.
Group: Binaries

%description bin
bin components for the wol package.


%package doc
Summary: doc components for the wol package.
Group: Documentation

%description doc
doc components for the wol package.


%package locales
Summary: locales components for the wol package.
Group: Default

%description locales
locales components for the wol package.


%prep
%setup -q -n wol-0.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510014114
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510014114
rm -rf %{buildroot}
%make_install
%find_lang wol

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wol
/usr/bin/wol-bootptab
/usr/bin/wol-dhcpdconf

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files locales -f wol.lang
%defattr(-,root,root,-)

